install: true
before_script:
  - bundle install
  - bundle exec xcake make
  - bundle exec pod install --verbose

script:
  - xcodebuild -workspace DemoCPIncrementalBug.xcworkspace -scheme DemoCPIncrementalBug -sdk iphonesimulator

matrix:
  include:
    - os: osx
      language: objective-c
      osx_image: xcode10.1